changes in news App
gillsheenu/NickelfoxAssignments-Sheenu pull request #3
Opened 2022-09-22 08:47 UTC by gillsheenu

2022-09-23 12:16 UTC, adhish-nickelfox requested changes

2022-09-23 12:16 UTC, adhish-nickelfox commented on app/src/main/res/layout/fragment_stop_watch.xml
> +
Use only constraint layout. Using linear inside constraint is redundant.

2022-09-27 07:28 UTC, pratikshit-nickelfox commented on app/src/main/res/layout/fragment_upload_image.xml
> -    tools:context=".UploadImageFragment">
Change Linear Layout to Constraint Layout

2022-09-27 07:29 UTC, pratikshit-nickelfox approved these changes
Changes reviewed

2022-09-29 09:27 UTC, adhish-nickelfox requested changes

2022-09-29 09:27 UTC, adhish-nickelfox commented on app/src/main/java/com/example/nickelffoxassignments_sheenu/news/ui/adapter/NewsAdapter.kt
> +                        progressbar.visibility = View.GONE
Use extension function for this
View.hide(){
this.visibility = View.GONE
}

2022-09-29 09:27 UTC, adhish-nickelfox commented on app/src/main/java/com/example/nickelffoxassignments_sheenu/news/ui/view/NewsHomeFragment.kt
> +                Toast.makeText(activity, "NO INTERNET ", Toast.LENGTH_SHORT).show()
Try using snackbar instead of Toasts

2022-09-29 09:27 UTC, adhish-nickelfox commented on app/src/main/java/com/example/nickelffoxassignments_sheenu/news/ui/view/NewsSearchFragment.kt
> +                emptyTextView.visibility = View.VISIBLE
Use extension function for this

2022-09-29 09:27 UTC, adhish-nickelfox commented on app/src/main/java/com/example/nickelffoxassignments_sheenu/uploadimage/ui/view/UploadImageFragment.kt
> +        uploadButton=view.findViewById(R.id.btnUpload)
Use view binding instead

2022-09-29 09:35 UTC, closed without merging