Feat/stopewatch
gillsheenu/NickelfoxAssignments-Sheenu pull request #4
Opened 2022-09-23 08:52 UTC by gillsheenu

2022-09-23 12:13 UTC, adhish-nickelfox commented on app/src/main/java/com/example/nickelffoxassignments_sheenu/MainActivity.kt
> +                    setAppBarColor(R.color.new_stop_watch_color)
Color name should be readable

2022-09-23 12:15 UTC, adhish-nickelfox requested changes

2022-09-23 12:15 UTC, adhish-nickelfox commented on app/src/main/res/layout/fragment_stop_watch.xml
Use constraint layout instead of Linear Layout @gillsheenu

2022-09-26 12:17 UTC, pratikshit-nickelfox reviewed
stop_watch_gradient.xml is not being used and is empty. It should be removed.

2022-09-29 09:15 UTC, adhish-nickelfox approved these changes
LGTM

2022-09-29 09:16 UTC, pratikshit-nickelfox commented
All changes reviewed. Ready to merge.

2022-09-29 09:16 UTC, merged